Query baking and in memory DB open.
godot-extended-libraries/godot-sqlite pull request #8
Opened 2020-07-30 09:26 UTC by AndreaCatania

## SQLiteQuery class
Added the possibility to bake a query so to speeding up the execution.
The added `SQLiteQuery` class has the possibility to execute the query and to execute it in batch.

Indeed you can submit a list of parameter and insert it with a single call. (Check the docs in the code)

## Open the DB in memory for volatile usage.

2020-08-01 10:50 UTC, madmiraal requested changes
See my [comments](https://github.com/godot-extended-libraries/godot-sqlite/pull/9#pullrequestreview-459563324) on #9, the PR against the `master` branch, regarding my expectation that this PR needs more work; even if it's just to ensure that it compiles. I've created a [PR](https://github.com/AndreaCatania/godot-sqlite/pull/2) to fix this PR to enable it to compile when applied to Godot 3.2 branch.

2020-08-01 10:50 UTC, madmiraal commented on sqlite.cpp
> +}
Missing `;`

2020-08-01 10:50 UTC, madmiraal commented on sqlite.h
> +
Missing `;`.

2020-10-10 14:49 UTC, fire commented
Testing in my projects, but ";" pr should be merged on top of this pr.

2020-10-10 15:31 UTC, AndreaCatania commented
Merged

2020-10-13 16:27 UTC, merged

2020-10-13 16:27 UTC, fire commented
Thanks.